FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy project files
COPY . .

# Set environment variables
ENV NODE_ENV=development

# Expose port
EXPOSE 8080

# Run the application in development mode
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 